#!/usr/bin/env python3
"""Draw image.png, the plugin icon Jellyfin shows in its plugin catalogue.

Kept in the repo so the icon is reproducible rather than an unexplained binary, and
regenerated by the release workflow so the picture always matches this script.

Shape matters more than it looks. Jellyfin renders the catalogue image as the whole
card background, cropped to fill, so a square full-bleed image gets scaled up until it
covers a card two and a half times wider than it is tall - which is how the first
version of this icon ended up looking enormous next to everything else. So: a wide
canvas at roughly the card's own proportions, a near-black background that blends into
the page the way the other plugins' cards do, and a mark occupying about a third of the
height, with enough margin that a crop at a different window width still looks right.

    python tools/make_image.py            # writes image.png
    python tools/make_image.py out.png    # writes somewhere else
"""

from __future__ import annotations

import sys

from PIL import Image, ImageDraw

# Close to the proportions Jellyfin's plugin cards actually use.
WIDTH = 800
HEIGHT = 320
SCALE = 3
W, H = WIDTH * SCALE, HEIGHT * SCALE

# Near-black, very slightly cool, so the card sits with its neighbours instead of
# announcing itself.
BG_TOP = (24, 26, 32)
BG_BOTTOM = (13, 14, 17)

# The mark's own colours. Deliberately not Jellyfin's palette - this is the plugin's.
MARK_TOP = (86, 166, 245)
MARK_BOTTOM = (150, 116, 240)

WHITE = 255


def vertical_gradient(top: tuple[int, int, int], bottom: tuple[int, int, int]) -> Image.Image:
    """A full-canvas vertical gradient between two colours."""
    column = Image.new("RGB", (1, H))
    for y in range(H):
        t = y / (H - 1)
        column.putpixel(
            (0, y),
            (
                round(top[0] + (bottom[0] - top[0]) * t),
                round(top[1] + (bottom[1] - top[1]) * t),
                round(top[2] + (bottom[2] - top[2]) * t),
            ),
        )
    return column.resize((W, H))


def mark_mask() -> Image.Image:
    """The speaker, its one sound arc, and a down arrow, as a mask to pour colour through.

    One arc, not two: at catalogue size a second faded one turned to mush. Coordinates
    are in unscaled canvas units and multiplied up, so the whole thing is drawn at 3x
    and downsampled rather than fighting PIL's non-antialiased primitives.
    """
    k = SCALE
    mask = Image.new("L", (W, H), 0)
    draw = ImageDraw.Draw(mask)

    # Speaker: a body and a cone, pointing right.
    draw.rectangle([302 * k, 144 * k, 332 * k, 176 * k], fill=WHITE)
    draw.polygon(
        [(332 * k, 144 * k), (368 * k, 108 * k), (368 * k, 212 * k), (332 * k, 176 * k)],
        fill=WHITE,
    )

    # One sound arc, springing from the mouth of the cone.
    radius = 30 * k
    cx, cy = 368 * k, 160 * k
    draw.arc(
        [cx - radius, cy - radius, cx + radius, cy + radius],
        start=-54,
        end=54,
        fill=WHITE,
        width=11 * k,
    )

    # A down arrow, well clear of the arc, so the icon still says "quieter" at 32px.
    x, thick = 472 * k, 12 * k
    draw.line([(x, 116 * k), (x, 202 * k)], fill=WHITE, width=thick)
    draw.line(
        [(451 * k, 181 * k), (x, 204 * k), (493 * k, 181 * k)],
        fill=WHITE,
        width=thick,
        joint="curve",
    )

    return mask


def main() -> int:
    out = sys.argv[1] if len(sys.argv) > 1 else "image.png"

    canvas = vertical_gradient(BG_TOP, BG_BOTTOM).convert("RGBA")
    canvas.paste(vertical_gradient(MARK_TOP, MARK_BOTTOM), (0, 0), mark_mask())

    canvas.resize((WIDTH, HEIGHT), Image.LANCZOS).save(out, "PNG", optimize=True)
    print(f"wrote {out} ({WIDTH}x{HEIGHT})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
